### ISSUE TITLE
Incluir URL para manual no About do projeto

### ISSUE THREAD

**Issue by caduvieira** [servicosgovbr/manual-integracao-assinatura-eletronica#1]
Incluir a URL depois de publicado no About do projeto

**Comment by edsonsl2001** [comment]
Ótima sugestão Cadu! Inclui a url provisória da documentação ainda em construção. Quando for concluída e criarmos o C_Name, atualizo para a URL definitiva.

**Comment by troyam** [comment]
Como migrar o staging para o normal?

**Comment by caduvieira** [comment]
Não entendi a pergunta. O que é o normal? E tem uma substring de staging na URL?
