### ISSUE TITLE
Não passa da etapa do sms

### ISSUE THREAD

**Issue by ricardosantosmti** [servicosgovbr/manual-integracao-assinatura-eletronica#4]
Mesmo após o cadastro no staging do gov.br, na tela de autorização do assinador o envio do sms não ocorre,
nunca chega o sms.
![telasms](https://user-images.githubusercontent.com/68597598/123868006-212f3700-d8fd-11eb-94c9-beb635a8b654.png)

**Comment by liviatsantos** [comment]
Olá @ricardosantosmti no ambiente de staging não é enviado o SMS. Deve ser usado o código 12345. Qualquer dúvida e para mais informações sobre a plataforma de assinatura avançada gov.br, peço por gentileza, entrar em contato através do email int-assinatura-govbr@economia.gov.br

**Comment by liviatsantos** [comment]
respondido
