### ISSUE TITLE
Remover PDF de GPG

### ISSUE THREAD

**Issue by caduvieira** [servicosgovbr/manual-integracao-assinatura-eletronica#6]
O manual está todo online mas a parte do GPG é um PDF. Incorporar essa parte GPG ao manual em RST/HTML.

**Comment by liviatsantos** [comment]
vamos fazer essa alteração @caduvieira

**Comment by liviatsantos** [comment]
@caduvieira  alteração realizada

**Comment by caduvieira** [comment]
Muito bom! Parabéns a todos aí!
