### ISSUE TITLE
Adicionar exemplo de aplicação para Assinatura envelopada

### ISSUE THREAD

**Issue by ericsonmoreira** [servicosgovbr/manual-integracao-assinatura-eletronica#9]
# Descrição

Adicionar um exemplo de aplicação em que se usar **assinatura envelopada**. 

## Motivação

Meu nome é Éricson Moreira, faço parte da equipe de desenvolvimento da **ESP** - Escola de Saúde Pública do CE. Uma dificuldade que encontramos na ESP é a confecção de certificados de cursos/treinamentos. Atualmente esse procedimento é feito de maneira totalmente manual. Gostaríamos de prover aos usuários de nossos serviços uma maneira prática, segura e confiável e ter os certificados dos cursos/treinamentos. Estamos tentando desenvolver uma integrando com o serviço do gov,br para assinatura de pdf. Encontramos o exemplo que mostra como implementar isso usando assinatura _detached_ mas gostaríamos de fazer isso com a assinatura envelopara. Apesar de ter uma sessão explicando como se fazer isso, não conseguimos evoluir nessa implementação.

Estamos bloqueados na parte de fazer o envelopamento. Seria interessante que a documentação oficial tivesse uma aplicação exemplo com essa implementação.

**Comment by ericsonmoreira** [comment]
Email para contato: ericson.moreira@esp.ce.gov.br

**Comment by caduvieira** [comment]
Nenhum dos exemplos do PDFBox https://github.com/apache/pdfbox/tree/trunk/examples/src/main/java/org/apache/pdfbox/examples/signature ou a documentação do DSS te ajudam https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/doc/dss-documentation.html#_specificities_of_signature_creation_in_different_signature_formats? 

E provavelmente você deve usar uma assinatura visual também por ser um certificado em PDF

**Comment by caduvieira** [comment]
E esclareço que esse serviço de assinatura avançada é para uma pessoa física ou jurídica assinar um documento para ser aceito por órgãos públicos ou entre órgãos do governo ou acordado previamente entre as partes conforme https://www.gov.br/governodigital/pt-br/assinatura-eletronica/saiba-mais-sobre-a-assinatura-eletronica

"No Brasil as assinaturas eletrônicas são válidas e reconhecidas legalmente. A [Lei nº 14.063, de 23 de Setembro de 2020](http://www.planalto.gov.br/ccivil_03/_ato2019-2022/2020/lei/l14063.htm), dispõe sobre as regras para uso das assinaturas eletrônicas nas interações entre pessoas e instituições privadas com os entes públicos e entre os próprios órgãos e entidades públicas."

**Comment by liviatsantos** [comment]
obrigada @caduvieira! @ericsonmoreira te mandarei por e-mail.

**Comment by ericsonmoreira** [comment]
@caduvieira esses exemplos que vc comentou não ajudaram muito. Mas obrigado pela resposta pelo e-mail. Vou dar uma olhada no que vcs me enviaram. Obrigado mais uma vez. 👍🏻
